pipeline {
  environment {
    registry = "hub.docker.com/udayangami"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent {
      docker{
          image 'maven:3-alpine'
          args '-v /root/.m2:/root/.m2'
      }
  }
  stages {
    stage('Build') {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
    }
    stage('Deliver') {
      steps{
        script {
          sh './jenkins/scripts/deliver.sh'
        }
      }
    }
    stage('Building image') {
        steps{
          script{
            dockerImage = docker.build registry + ":$BUILD_NUMBER"
          }
        }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
  }
}
